apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-website
  labels:
    app: capstone-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-website
  template:
    metadata:
      labels:
        app: capstone-website
    spec:
      containers:
      - name: capstone-website
        image: kaushal2608/capstone-website:latest
        ports:
        - containerPort: 80
